"""Index generation for Keep.

Generates `index.md` at the workspace root — a Markdown table cataloguing
all non-private documents in the workspace. The LLM reads this first at the
start of every session to locate relevant pages before drilling into them.

The index is deterministic and tool-owned. It is rebuilt in full on every
`keep index` run. Private documents are excluded.

Typical usage::

    from keep.index import build, write

    settings = Settings.load(workspace)
    rows = build(settings)
    write(rows, settings)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from keep.logging import get_logger
from keep.settings import Settings
from keep.utils.frontmatter import FrontmatterError, parse


log = get_logger(__name__)

#: Header comment written at the top of index.md.
_HEADER_COMMENT = "<!-- Auto-generated by keep. Do not edit. -->"

#: Column headers for the index table.
_COLUMNS = ("slug", "title", "kind", "status", "summary")


@dataclass
class IndexRow:
    """A single row in the index table.

    Attributes:
        slug: Unique document identifier.
        title: Human-readable document title.
        kind: Semantic document kind (e.g. ``recipe``, ``person``).
        status: Lifecycle status.
        summary: One-line summary authored by the LLM. Empty string if absent.
    """

    slug: str
    title: str
    kind: str
    status: str
    summary: str


def build(settings: Settings) -> list[IndexRow]:
    """Build the index rows by walking all non-private workspace documents.

    Documents that fail frontmatter parsing are skipped with a warning.
    Results are sorted alphabetically by slug for deterministic output.

    Args:
        settings: Resolved workspace settings.

    Returns:
        Sorted list of :class:`IndexRow` instances.
    """
    keep_dir_name = settings.keep_dir.name
    rows = []

    for path in sorted(settings.workspace.rglob("*.md")):
        if keep_dir_name in path.relative_to(settings.workspace).parts:
            continue

        if path == settings.index_path:
            continue

        try:
            doc = parse(path)
        except FrontmatterError as exc:
            log.warning(
                "skipping %s: %s",
                path.relative_to(settings.workspace),
                exc,
            )
            continue

        if doc.private:
            log.debug("excluding private document: %s", doc.slug)
            continue

        rows.append(
            IndexRow(
                slug=doc.slug,
                title=doc.title,
                kind=doc.kind,
                status=doc.status,
                summary=doc.summary or "",
            )
        )

    return sorted(rows, key=lambda r: r.slug)


def write(rows: list[IndexRow], settings: Settings) -> Path:
    """Write the index table to `index.md` at the workspace root.

    Args:
        rows: Index rows as returned by :func:`build`.
        settings: Resolved workspace settings.

    Returns:
        Path to the written file.
    """
    settings.index_path.write_text(
        _render(rows),
        encoding="utf-8",
    )
    return settings.index_path


def _render(rows: list[IndexRow]) -> str:
    """Render index rows as a Markdown table string.

    Args:
        rows: Index rows to render.

    Returns:
        Full Markdown content for `index.md`, including the header comment.
    """
    lines = [
        _HEADER_COMMENT,
        "",
        _table_row(_COLUMNS),
        _separator_row(_COLUMNS),
    ]

    for row in rows:
        lines.append(
            _table_row(
                (
                    row.slug,
                    row.title,
                    row.kind,
                    row.status,
                    row.summary,
                )
            )
        )

    lines.append("")
    return "\n".join(lines)


def _table_row(cells: tuple[str, ...]) -> str:
    """Format a sequence of cell values as a Markdown table row.

    Args:
        cells: Cell values in column order.

    Returns:
        Markdown table row string.
    """
    return "| " + " | ".join(cells) + " |"


def _separator_row(columns: tuple[str, ...]) -> str:
    """Generate the separator row beneath the header.

    Each separator cell is sized to match its column header.

    Args:
        columns: Column header names.

    Returns:
        Markdown separator row string.
    """
    return "| " + " | ".join("-" * len(col) for col in columns) + " |"
