"""Tests for `keep.cli`."""

from __future__ import annotations

import sys
import json
import subprocess

from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _run_keep(*args: str, cwd: Path) -> subprocess.CompletedProcess[str]:
    """Run the `keep` CLI as a subprocess.

    Args:
        *args: Subcommand and arguments to pass to `keep`.
        cwd: Working directory to run from (should be a workspace root).

    Returns:
        Completed process result.
    """
    return subprocess.run(  # noqa: S603
        [sys.executable, "-m", "keep.cli", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
    )


# ---------------------------------------------------------------------------
# Workspace resolution
# ---------------------------------------------------------------------------


class TestWorkspaceResolution:
    """CLI behaviour when keep.yml is present or absent."""

    def test_exits_with_error_when_no_config(self, tmp_path: Path) -> None:
        result = _run_keep("graph", cwd=tmp_path)

        assert result.returncode != 0
        assert "keep.yml" in result.stderr

    def test_error_message_suggests_workspace_root(
        self, tmp_path: Path
    ) -> None:
        result = _run_keep("graph", cwd=tmp_path)

        assert "workspace root" in result.stderr


# ---------------------------------------------------------------------------
# keep graph
# ---------------------------------------------------------------------------


class TestCmdGraph:
    """CLI `keep graph` subcommand."""

    def test_graph_exits_zero(self, workspace: Path) -> None:
        result = _run_keep("graph", cwd=workspace)

        assert result.returncode == 0

    def test_graph_creates_graph_json(self, workspace: Path) -> None:
        _run_keep("graph", cwd=workspace)

        assert (workspace / ".keep" / "graph.json").exists()

    def test_graph_output_reports_node_count(self, workspace: Path) -> None:
        result = _run_keep("graph", cwd=workspace)

        assert "node(s)" in result.stdout

    def test_graph_output_reports_edge_count(self, workspace: Path) -> None:
        result = _run_keep("graph", cwd=workspace)

        assert "edge(s)" in result.stdout

    def test_graph_json_is_valid(self, workspace: Path) -> None:
        _run_keep("graph", cwd=workspace)
        content = (workspace / ".keep" / "graph.json").read_text(
            encoding="utf-8"
        )
        parsed = json.loads(content)

        assert "nodes" in parsed
        assert "edges" in parsed


# ---------------------------------------------------------------------------
# keep index
# ---------------------------------------------------------------------------


class TestCmdIndex:
    """CLI `keep index` subcommand."""

    def test_index_exits_zero(self, workspace: Path) -> None:
        result = _run_keep("index", cwd=workspace)

        assert result.returncode == 0

    def test_index_creates_index_md(self, workspace: Path) -> None:
        _run_keep("index", cwd=workspace)

        assert (workspace / "index.md").exists()

    def test_index_output_reports_document_count(self, workspace: Path) -> None:
        result = _run_keep("index", cwd=workspace)

        assert "document(s)" in result.stdout

    def test_index_md_contains_header_comment(self, workspace: Path) -> None:
        _run_keep("index", cwd=workspace)
        content = (workspace / "index.md").read_text(encoding="utf-8")

        assert "Auto-generated by keep" in content


# ---------------------------------------------------------------------------
# keep state
# ---------------------------------------------------------------------------


class TestCmdState:
    """CLI `keep state` subcommand."""

    def test_state_exits_zero(self, workspace: Path) -> None:
        result = _run_keep("state", cwd=workspace)

        assert result.returncode == 0

    def test_state_creates_state_json(self, workspace: Path) -> None:
        _run_keep("state", cwd=workspace)

        assert (workspace / ".keep" / "state.json").exists()

    def test_state_output_reports_document_count(self, workspace: Path) -> None:
        result = _run_keep("state", cwd=workspace)

        assert "document(s)" in result.stdout

    def test_state_json_is_valid(self, workspace: Path) -> None:
        _run_keep("state", cwd=workspace)
        content = (workspace / ".keep" / "state.json").read_text(
            encoding="utf-8"
        )
        parsed = json.loads(content)

        assert "documents" in parsed
        assert "schema_version" in parsed


# ---------------------------------------------------------------------------
# keep lint
# ---------------------------------------------------------------------------


class TestCmdLint:
    """CLI `keep lint` subcommand."""

    def test_lint_exits_zero_on_clean_workspace(self, workspace: Path) -> None:
        result = _run_keep("lint", cwd=workspace)

        assert result.returncode == 0

    def test_lint_creates_lint_json(self, workspace: Path) -> None:
        _run_keep("lint", cwd=workspace)

        assert (workspace / ".keep" / "lint.json").exists()

    def test_lint_output_reports_summary(self, workspace: Path) -> None:
        result = _run_keep("lint", cwd=workspace)

        assert "document(s)" in result.stdout

    def test_lint_exits_nonzero_on_violations(self, workspace: Path) -> None:
        # Introduce a dangling slug in a published document.
        ragu_path = workspace / "recipes" / "ragu.md"
        content = ragu_path.read_text(encoding="utf-8")
        ragu_path.write_text(
            content.replace("target: soffritto", "target: ghost-doc"),
            encoding="utf-8",
        )

        result = _run_keep("lint", cwd=workspace)

        assert result.returncode == 1

    def test_lint_output_shows_violation_details(self, workspace: Path) -> None:
        ragu_path = workspace / "recipes" / "ragu.md"
        content = ragu_path.read_text(encoding="utf-8")
        ragu_path.write_text(
            content.replace("target: soffritto", "target: ghost-doc"),
            encoding="utf-8",
        )

        result = _run_keep("lint", cwd=workspace)

        assert "dangling_slug" in result.stdout

    def test_lint_report_written_to_keep_dir(self, workspace: Path) -> None:
        _run_keep("lint", cwd=workspace)
        content = (workspace / ".keep" / "lint.json").read_text(
            encoding="utf-8"
        )
        parsed = json.loads(content)

        assert "summary" in parsed
        assert "documents" in parsed


# ---------------------------------------------------------------------------
# Global flags
# ---------------------------------------------------------------------------


class TestGlobalFlags:
    """Global CLI flags."""

    def test_help_exits_zero(self, workspace: Path) -> None:
        result = _run_keep("--help", cwd=workspace)

        assert result.returncode == 0

    def test_help_lists_subcommands(self, workspace: Path) -> None:
        result = _run_keep("--help", cwd=workspace)

        assert "graph" in result.stdout
        assert "index" in result.stdout
        assert "lint" in result.stdout
        assert "state" in result.stdout

    def test_verbose_flag_accepted(self, workspace: Path) -> None:
        result = _run_keep("--verbose", "graph", cwd=workspace)

        assert result.returncode == 0

    def test_no_subcommand_exits_nonzero(self, workspace: Path) -> None:
        result = _run_keep(cwd=workspace)

        assert result.returncode != 0
